"""GENERATO da scripts/gen_juggler_protocol.py. NON si modifica a mano.

Fonte: omni.ja!chrome/juggler/content/protocol/Protocol.js
Comandi: 71   Eventi: 34

Il browser applica questo schema a MONDO CHIUSO: un campo non dichiarato viene
RIFIUTATO a runtime, non ignorato. Serve quindi a verificare cio' che MANDIAMO
prima che parta, non a documentare.

⛔ Non sostituisce `protocol_drift_check.py` nel repo del sorgente: quel gate
chiede cosa manda un client VERO, ed e' una domanda che questo file non puo'
porre, perche' e' generato dalla stessa fonte che dovrebbe controllare.
"""
from __future__ import annotations

DOMINI = ['Browser', 'Heap', 'Network', 'Page', 'Runtime']

COMANDI = {'Browser.addBinding': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                  'k': 'Optional'},
                                             'name': {'k': 'String'},
                                             'script': {'k': 'String'},
                                             'worldName': {'di': {'k': 'String'},
                                                           'k': 'Optional'}},
                                   'k': 'Object'},
                        'returns': None},
 'Browser.cancelDownload': {'params': {'campi': {'uuid': {'di': {'k': 'String'},
                                                          'k': 'Optional'}},
                                       'k': 'Object'},
                            'returns': None},
 'Browser.clearCache': {'params': None, 'returns': None},
 'Browser.clearCookies': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                    'k': 'Optional'}},
                                     'k': 'Object'},
                          'returns': None},
 'Browser.close': {'params': None, 'returns': None},
 'Browser.createBrowserContext': {'params': {'campi': {'removeOnDetach': {'di': {'k': 'Boolean'},
                                                                          'k': 'Optional'}},
                                             'k': 'Object'},
                                  'returns': {'campi': {'browserContextId': {'k': 'String'}},
                                              'k': 'Object'}},
 'Browser.enable': {'params': {'campi': {'attachToDefaultContext': {'k': 'Boolean'},
                                         'userPrefs': {'di': {'di': {'campi': {'name': {'k': 'String'},
                                                                               'value': {'k': 'Any'}},
                                                                     'k': 'Object',
                                                                     'rif': 'browserTypes.UserPreference'},
                                                              'k': 'Array'},
                                                       'k': 'Optional'}},
                               'k': 'Object'},
                    'returns': None},
 'Browser.getCookies': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                  'k': 'Optional'}},
                                   'k': 'Object'},
                        'returns': {'campi': {'cookies': {'di': {'campi': {'domain': {'k': 'String'},
                                                                           'expires': {'k': 'Number'},
                                                                           'httpOnly': {'k': 'Boolean'},
                                                                           'name': {'k': 'String'},
                                                                           'path': {'k': 'String'},
                                                                           'sameSite': {'k': 'Enum',
                                                                                        'valori': ['Strict',
                                                                                                   'Lax',
                                                                                                   'None']},
                                                                           'secure': {'k': 'Boolean'},
                                                                           'session': {'k': 'Boolean'},
                                                                           'size': {'k': 'Number'},
                                                                           'value': {'k': 'String'}},
                                                                 'k': 'Object',
                                                                 'rif': 'browserTypes.Cookie'},
                                                          'k': 'Array'}},
                                    'k': 'Object'}},
 'Browser.getInfo': {'params': None,
                     'returns': {'campi': {'userAgent': {'k': 'String'},
                                           'version': {'k': 'String'}},
                                 'k': 'Object'}},
 'Browser.grantPermissions': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                        'k': 'Optional'},
                                                   'origin': {'k': 'String'},
                                                   'permissions': {'di': {'k': 'String'},
                                                                   'k': 'Array'}},
                                         'k': 'Object'},
                              'returns': None},
 'Browser.newPage': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                               'k': 'Optional'}},
                                'k': 'Object'},
                     'returns': {'campi': {'targetId': {'k': 'String'}},
                                 'k': 'Object'}},
 'Browser.removeBrowserContext': {'params': {'campi': {'browserContextId': {'k': 'String'}},
                                             'k': 'Object'},
                                  'returns': None},
 'Browser.resetPermissions': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                        'k': 'Optional'}},
                                         'k': 'Object'},
                              'returns': None},
 'Browser.setBrowserProxy': {'params': {'campi': {'bypass': {'di': {'k': 'String'},
                                                             'k': 'Array'},
                                                  'host': {'k': 'String'},
                                                  'password': {'di': {'k': 'String'},
                                                               'k': 'Optional'},
                                                  'port': {'k': 'Number'},
                                                  'type': {'k': 'Enum',
                                                           'valori': ['http',
                                                                      'https',
                                                                      'socks',
                                                                      'socks4']},
                                                  'username': {'di': {'k': 'String'},
                                                               'k': 'Optional'}},
                                        'k': 'Object'},
                             'returns': None},
 'Browser.setBypassCSP': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                    'k': 'Optional'},
                                               'bypassCSP': {'di': {'k': 'Boolean'},
                                                             'k': 'Nullable'}},
                                     'k': 'Object'},
                          'returns': None},
 'Browser.setCacheDisabled': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                        'k': 'Optional'},
                                                   'cacheDisabled': {'k': 'Boolean'}},
                                         'k': 'Object'},
                              'returns': None},
 'Browser.setColorScheme': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                      'k': 'Optional'},
                                                 'colorScheme': {'di': {'k': 'Enum',
                                                                        'valori': ['dark',
                                                                                   'light',
                                                                                   'no-preference']},
                                                                 'k': 'Nullable'}},
                                       'k': 'Object'},
                            'returns': None},
 'Browser.setContextProxy': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                       'k': 'Optional'},
                                                  'bypass': {'di': {'k': 'String'},
                                                             'k': 'Array'},
                                                  'host': {'k': 'String'},
                                                  'password': {'di': {'k': 'String'},
                                                               'k': 'Optional'},
                                                  'port': {'k': 'Number'},
                                                  'type': {'k': 'Enum',
                                                           'valori': ['http',
                                                                      'https',
                                                                      'socks',
                                                                      'socks4']},
                                                  'username': {'di': {'k': 'String'},
                                                               'k': 'Optional'}},
                                        'k': 'Object'},
                             'returns': None},
 'Browser.setContrast': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                   'k': 'Optional'},
                                              'contrast': {'di': {'k': 'Enum',
                                                                  'valori': ['less',
                                                                             'more',
                                                                             'custom',
                                                                             'no-preference']},
                                                           'k': 'Nullable'}},
                                    'k': 'Object'},
                         'returns': None},
 'Browser.setCookies': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                  'k': 'Optional'},
                                             'cookies': {'di': {'campi': {'domain': {'di': {'k': 'String'},
                                                                                     'k': 'Optional'},
                                                                          'expires': {'di': {'k': 'Number'},
                                                                                      'k': 'Optional'},
                                                                          'httpOnly': {'di': {'k': 'Boolean'},
                                                                                       'k': 'Optional'},
                                                                          'name': {'k': 'String'},
                                                                          'path': {'di': {'k': 'String'},
                                                                                   'k': 'Optional'},
                                                                          'sameSite': {'di': {'k': 'Enum',
                                                                                              'valori': ['Strict',
                                                                                                         'Lax',
                                                                                                         'None']},
                                                                                       'k': 'Optional'},
                                                                          'secure': {'di': {'k': 'Boolean'},
                                                                                     'k': 'Optional'},
                                                                          'url': {'di': {'k': 'String'},
                                                                                  'k': 'Optional'},
                                                                          'value': {'k': 'String'}},
                                                                'k': 'Object',
                                                                'rif': 'browserTypes.CookieOptions'},
                                                         'k': 'Array'}},
                                   'k': 'Object'},
                        'returns': None},
 'Browser.setDefaultViewport': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                          'k': 'Optional'},
                                                     'viewport': {'di': {'campi': {'deviceScaleFactor': {'di': {'k': 'Number'},
                                                                                                         'k': 'Optional'},
                                                                                   'isMobile': {'di': {'k': 'Boolean'},
                                                                                                'k': 'Optional'},
                                                                                   'screenSize': {'di': {'di': {'campi': {'height': {'k': 'Number'},
                                                                                                                          'width': {'k': 'Number'}},
                                                                                                                'k': 'Object',
                                                                                                                'rif': 'pageTypes.Size'},
                                                                                                         'k': 'Nullable'},
                                                                                                  'k': 'Optional'},
                                                                                   'viewportSize': {'campi': {'height': {'k': 'Number'},
                                                                                                              'width': {'k': 'Number'}},
                                                                                                    'k': 'Object',
                                                                                                    'rif': 'pageTypes.Size'}},
                                                                         'k': 'Object',
                                                                         'rif': 'pageTypes.Viewport'},
                                                                  'k': 'Nullable'}},
                                           'k': 'Object'},
                                'returns': None},
 'Browser.setDownloadOptions': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                          'k': 'Optional'},
                                                     'downloadOptions': {'di': {'campi': {'behavior': {'di': {'k': 'Enum',
                                                                                                              'valori': ['saveToDisk',
                                                                                                                         'cancel']},
                                                                                                       'k': 'Optional'},
                                                                                          'downloadsDir': {'di': {'k': 'String'},
                                                                                                           'k': 'Optional'}},
                                                                                'k': 'Object',
                                                                                'rif': 'browserTypes.DownloadOptions'},
                                                                         'k': 'Nullable'}},
                                           'k': 'Object'},
                                'returns': None},
 'Browser.setExtraHTTPHeaders': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                           'k': 'Optional'},
                                                      'headers': {'di': {'campi': {'name': {'k': 'String'},
                                                                                   'value': {'k': 'String'}},
                                                                         'k': 'Object',
                                                                         'rif': 'networkTypes.HTTPHeader'},
                                                                  'k': 'Array'}},
                                            'k': 'Object'},
                                 'returns': None},
 'Browser.setForcedColors': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                       'k': 'Optional'},
                                                  'forcedColors': {'di': {'k': 'Enum',
                                                                          'valori': ['active',
                                                                                     'none']},
                                                                   'k': 'Nullable'}},
                                        'k': 'Object'},
                             'returns': None},
 'Browser.setGeolocationOverride': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                              'k': 'Optional'},
                                                         'geolocation': {'di': {'campi': {'accuracy': {'di': {'k': 'Number'},
                                                                                                       'k': 'Optional'},
                                                                                          'latitude': {'k': 'Number'},
                                                                                          'longitude': {'k': 'Number'}},
                                                                                'k': 'Object',
                                                                                'rif': 'browserTypes.Geolocation'},
                                                                         'k': 'Nullable'}},
                                               'k': 'Object'},
                                    'returns': None},
 'Browser.setHTTPCredentials': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                          'k': 'Optional'},
                                                     'credentials': {'di': {'campi': {'origin': {'di': {'k': 'String'},
                                                                                                 'k': 'Optional'},
                                                                                      'password': {'k': 'String'},
                                                                                      'username': {'k': 'String'}},
                                                                            'k': 'Object',
                                                                            'rif': 'networkTypes.HTTPCredentials'},
                                                                     'k': 'Nullable'}},
                                           'k': 'Object'},
                                'returns': None},
 'Browser.setIgnoreHTTPSErrors': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                            'k': 'Optional'},
                                                       'ignoreHTTPSErrors': {'di': {'k': 'Boolean'},
                                                                             'k': 'Nullable'}},
                                             'k': 'Object'},
                                  'returns': None},
 'Browser.setInitScripts': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                      'k': 'Optional'},
                                                 'scripts': {'di': {'campi': {'script': {'k': 'String'},
                                                                              'worldName': {'di': {'k': 'String'},
                                                                                            'k': 'Optional'}},
                                                                    'k': 'Object',
                                                                    'rif': 'pageTypes.InitScript'},
                                                             'k': 'Array'}},
                                       'k': 'Object'},
                            'returns': None},
 'Browser.setJavaScriptDisabled': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                             'k': 'Optional'},
                                                        'javaScriptDisabled': {'k': 'Boolean'}},
                                              'k': 'Object'},
                                   'returns': None},
 'Browser.setLocaleOverride': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                         'k': 'Optional'},
                                                    'locale': {'di': {'k': 'String'},
                                                               'k': 'Nullable'}},
                                          'k': 'Object'},
                               'returns': None},
 'Browser.setOnlineOverride': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                         'k': 'Optional'},
                                                    'override': {'di': {'k': 'Enum',
                                                                        'valori': ['online',
                                                                                   'offline']},
                                                                 'k': 'Nullable'}},
                                          'k': 'Object'},
                               'returns': None},
 'Browser.setReducedMotion': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                        'k': 'Optional'},
                                                   'reducedMotion': {'di': {'k': 'Enum',
                                                                            'valori': ['reduce',
                                                                                       'no-preference']},
                                                                     'k': 'Nullable'}},
                                         'k': 'Object'},
                              'returns': None},
 'Browser.setRequestInterception': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                              'k': 'Optional'},
                                                         'enabled': {'k': 'Boolean'}},
                                               'k': 'Object'},
                                    'returns': None},
 'Browser.setTimezoneOverride': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                           'k': 'Optional'},
                                                      'timezoneId': {'di': {'k': 'String'},
                                                                     'k': 'Nullable'}},
                                            'k': 'Object'},
                                 'returns': None},
 'Browser.setTouchOverride': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                        'k': 'Optional'},
                                                   'hasTouch': {'di': {'k': 'Boolean'},
                                                                'k': 'Nullable'}},
                                         'k': 'Object'},
                              'returns': None},
 'Browser.setUserAgentOverride': {'params': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                            'k': 'Optional'},
                                                       'userAgent': {'di': {'k': 'String'},
                                                                     'k': 'Nullable'}},
                                             'k': 'Object'},
                                  'returns': None},
 'Heap.collectGarbage': {'params': {'campi': {}, 'k': 'Object'}, 'returns': None},
 'Network.abortInterceptedRequest': {'params': {'campi': {'errorCode': {'k': 'String'},
                                                          'requestId': {'k': 'String'}},
                                                'k': 'Object'},
                                     'returns': None},
 'Network.fulfillInterceptedRequest': {'params': {'campi': {'base64body': {'di': {'k': 'String'},
                                                                           'k': 'Optional'},
                                                            'headers': {'di': {'campi': {'name': {'k': 'String'},
                                                                                         'value': {'k': 'String'}},
                                                                               'k': 'Object',
                                                                               'rif': 'networkTypes.HTTPHeader'},
                                                                        'k': 'Array'},
                                                            'requestId': {'k': 'String'},
                                                            'status': {'k': 'Number'},
                                                            'statusText': {'k': 'String'}},
                                                  'k': 'Object'},
                                       'returns': None},
 'Network.resumeInterceptedRequest': {'params': {'campi': {'headers': {'di': {'di': {'campi': {'name': {'k': 'String'},
                                                                                               'value': {'k': 'String'}},
                                                                                     'k': 'Object',
                                                                                     'rif': 'networkTypes.HTTPHeader'},
                                                                              'k': 'Array'},
                                                                       'k': 'Optional'},
                                                           'method': {'di': {'k': 'String'},
                                                                      'k': 'Optional'},
                                                           'postData': {'di': {'k': 'String'},
                                                                        'k': 'Optional'},
                                                           'requestId': {'k': 'String'},
                                                           'url': {'di': {'k': 'String'},
                                                                   'k': 'Optional'}},
                                                 'k': 'Object'},
                                      'returns': None},
 'Network.setExtraHTTPHeaders': {'params': {'campi': {'headers': {'di': {'campi': {'name': {'k': 'String'},
                                                                                   'value': {'k': 'String'}},
                                                                         'k': 'Object',
                                                                         'rif': 'networkTypes.HTTPHeader'},
                                                                  'k': 'Array'}},
                                            'k': 'Object'},
                                 'returns': None},
 'Network.setRequestInterception': {'params': {'campi': {'enabled': {'k': 'Boolean'}},
                                               'k': 'Object'},
                                    'returns': None},
 'Page.adoptNode': {'params': {'campi': {'executionContextId': {'k': 'String'},
                                         'frameId': {'k': 'String'},
                                         'objectId': {'di': {'k': 'String'},
                                                      'k': 'Optional'}},
                               'k': 'Object'},
                    'returns': {'campi': {'remoteObject': {'di': {'campi': {'objectId': {'di': {'k': 'String'},
                                                                                         'k': 'Optional'},
                                                                            'subtype': {'di': {'k': 'Enum',
                                                                                               'valori': ['array',
                                                                                                          'null',
                                                                                                          'node',
                                                                                                          'regexp',
                                                                                                          'date',
                                                                                                          'map',
                                                                                                          'set',
                                                                                                          'weakmap',
                                                                                                          'weakset',
                                                                                                          'error',
                                                                                                          'proxy',
                                                                                                          'promise',
                                                                                                          'typedarray']},
                                                                                        'k': 'Optional'},
                                                                            'type': {'di': {'k': 'Enum',
                                                                                            'valori': ['object',
                                                                                                       'function',
                                                                                                       'undefined',
                                                                                                       'string',
                                                                                                       'number',
                                                                                                       'boolean',
                                                                                                       'symbol',
                                                                                                       'bigint']},
                                                                                     'k': 'Optional'},
                                                                            'unserializableValue': {'di': {'k': 'Enum',
                                                                                                           'valori': ['Infinity',
                                                                                                                      '-Infinity',
                                                                                                                      '-0',
                                                                                                                      'NaN']},
                                                                                                    'k': 'Optional'},
                                                                            'value': {'k': 'Any'}},
                                                                  'k': 'Object',
                                                                  'rif': 'runtimeTypes.RemoteObject'},
                                                           'k': 'Nullable'}},
                                'k': 'Object'}},
 'Page.bringToFront': {'params': {'campi': {}, 'k': 'Object'}, 'returns': None},
 'Page.close': {'params': {'campi': {'runBeforeUnload': {'di': {'k': 'Boolean'},
                                                         'k': 'Optional'}},
                           'k': 'Object'},
                'returns': None},
 'Page.describeNode': {'params': {'campi': {'frameId': {'k': 'String'},
                                            'objectId': {'k': 'String'}},
                                  'k': 'Object'},
                       'returns': {'campi': {'contentFrameId': {'di': {'k': 'String'},
                                                                'k': 'Optional'},
                                             'ownerFrameId': {'di': {'k': 'String'},
                                                              'k': 'Optional'}},
                                   'k': 'Object'}},
 'Page.dispatchKeyEvent': {'params': {'campi': {'code': {'k': 'String'},
                                                'key': {'k': 'String'},
                                                'keyCode': {'k': 'Number'},
                                                'location': {'k': 'Number'},
                                                'repeat': {'k': 'Boolean'},
                                                'text': {'di': {'k': 'String'},
                                                         'k': 'Optional'},
                                                'type': {'k': 'String'}},
                                      'k': 'Object'},
                           'returns': None},
 'Page.dispatchMouseEvent': {'params': {'campi': {'button': {'k': 'Number'},
                                                  'buttons': {'k': 'Number'},
                                                  'clickCount': {'di': {'k': 'Number'},
                                                                 'k': 'Optional'},
                                                  'modifiers': {'k': 'Number'},
                                                  'type': {'k': 'Enum',
                                                           'valori': ['mousedown',
                                                                      'mousemove',
                                                                      'mouseup']},
                                                  'x': {'k': 'Number'},
                                                  'y': {'k': 'Number'}},
                                        'k': 'Object'},
                             'returns': None},
 'Page.dispatchTapEvent': {'params': {'campi': {'modifiers': {'k': 'Number'},
                                                'x': {'k': 'Number'},
                                                'y': {'k': 'Number'}},
                                      'k': 'Object'},
                           'returns': None},
 'Page.dispatchTrustedInputEvents': {'params': {'campi': {'frameId': {'k': 'String'},
                                                          'objectId': {'k': 'String'},
                                                          'types': {'di': {'k': 'String'},
                                                                    'k': 'Array'}},
                                                'k': 'Object'},
                                     'returns': None},
 'Page.dispatchWheelEvent': {'params': {'campi': {'deltaX': {'k': 'Number'},
                                                  'deltaY': {'k': 'Number'},
                                                  'deltaZ': {'k': 'Number'},
                                                  'modifiers': {'k': 'Number'},
                                                  'x': {'k': 'Number'},
                                                  'y': {'k': 'Number'}},
                                        'k': 'Object'},
                             'returns': None},
 'Page.getContentQuads': {'params': {'campi': {'frameId': {'k': 'String'},
                                               'objectId': {'k': 'String'}},
                                     'k': 'Object'},
                          'returns': {'campi': {'quads': {'di': {'campi': {'p1': {'campi': {'x': {'k': 'Number'},
                                                                                            'y': {'k': 'Number'}},
                                                                                  'k': 'Object',
                                                                                  'rif': 'pageTypes.DOMPoint'},
                                                                           'p2': {'campi': {'x': {'k': 'Number'},
                                                                                            'y': {'k': 'Number'}},
                                                                                  'k': 'Object',
                                                                                  'rif': 'pageTypes.DOMPoint'},
                                                                           'p3': {'campi': {'x': {'k': 'Number'},
                                                                                            'y': {'k': 'Number'}},
                                                                                  'k': 'Object',
                                                                                  'rif': 'pageTypes.DOMPoint'},
                                                                           'p4': {'campi': {'x': {'k': 'Number'},
                                                                                            'y': {'k': 'Number'}},
                                                                                  'k': 'Object',
                                                                                  'rif': 'pageTypes.DOMPoint'}},
                                                                 'k': 'Object',
                                                                 'rif': 'pageTypes.DOMQuad'},
                                                          'k': 'Array'}},
                                      'k': 'Object'}},
 'Page.goBack': {'params': {'campi': {'frameId': {'k': 'String'}}, 'k': 'Object'},
                 'returns': {'campi': {'success': {'k': 'Boolean'}}, 'k': 'Object'}},
 'Page.goForward': {'params': {'campi': {'frameId': {'k': 'String'}}, 'k': 'Object'},
                    'returns': {'campi': {'success': {'k': 'Boolean'}}, 'k': 'Object'}},
 'Page.handleDialog': {'params': {'campi': {'accept': {'k': 'Boolean'},
                                            'dialogId': {'k': 'String'},
                                            'promptText': {'di': {'k': 'String'},
                                                           'k': 'Optional'}},
                                  'k': 'Object'},
                       'returns': None},
 'Page.insertText': {'params': {'campi': {'text': {'k': 'String'}}, 'k': 'Object'},
                     'returns': None},
 'Page.navigate': {'params': {'campi': {'frameId': {'k': 'String'},
                                        'referer': {'di': {'k': 'String'},
                                                    'k': 'Optional'},
                                        'url': {'k': 'String'}},
                              'k': 'Object'},
                   'returns': {'campi': {'navigationId': {'di': {'k': 'String'},
                                                          'k': 'Nullable'}},
                               'k': 'Object'}},
 'Page.reload': {'params': {'campi': {}, 'k': 'Object'}, 'returns': None},
 'Page.screenshot': {'params': {'campi': {'clip': {'campi': {'height': {'k': 'Number'},
                                                             'width': {'k': 'Number'},
                                                             'x': {'k': 'Number'},
                                                             'y': {'k': 'Number'}},
                                                   'k': 'Object',
                                                   'rif': 'pageTypes.Clip'},
                                          'mimeType': {'k': 'Enum',
                                                       'valori': ['image/png',
                                                                  'image/jpeg']},
                                          'omitDeviceScaleFactor': {'di': {'k': 'Boolean'},
                                                                    'k': 'Optional'},
                                          'quality': {'di': {'k': 'Number'},
                                                      'k': 'Optional'}},
                                'k': 'Object'},
                     'returns': {'campi': {'data': {'k': 'String'}}, 'k': 'Object'}},
 'Page.scrollIntoViewIfNeeded': {'params': {'campi': {'frameId': {'k': 'String'},
                                                      'objectId': {'k': 'String'},
                                                      'rect': {'di': {'campi': {'height': {'k': 'Number'},
                                                                                'width': {'k': 'Number'},
                                                                                'x': {'k': 'Number'},
                                                                                'y': {'k': 'Number'}},
                                                                      'k': 'Object',
                                                                      'rif': 'pageTypes.Rect'},
                                                               'k': 'Optional'}},
                                            'k': 'Object'},
                                 'returns': None},
 'Page.sendMessageToWorker': {'params': {'campi': {'frameId': {'k': 'String'},
                                                   'message': {'k': 'String'},
                                                   'workerId': {'k': 'String'}},
                                         'k': 'Object'},
                              'returns': None},
 'Page.setCacheDisabled': {'params': {'campi': {'cacheDisabled': {'k': 'Boolean'}},
                                      'k': 'Object'},
                           'returns': None},
 'Page.setEmulatedMedia': {'params': {'campi': {'colorScheme': {'di': {'k': 'Enum',
                                                                       'valori': ['dark',
                                                                                  'light',
                                                                                  'no-preference']},
                                                                'k': 'Optional'},
                                                'contrast': {'di': {'k': 'Enum',
                                                                    'valori': ['less',
                                                                               'more',
                                                                               'custom',
                                                                               'no-preference']},
                                                             'k': 'Optional'},
                                                'forcedColors': {'di': {'k': 'Enum',
                                                                        'valori': ['active',
                                                                                   'none']},
                                                                 'k': 'Optional'},
                                                'reducedMotion': {'di': {'k': 'Enum',
                                                                         'valori': ['reduce',
                                                                                    'no-preference']},
                                                                  'k': 'Optional'},
                                                'type': {'di': {'k': 'Enum',
                                                                'valori': ['screen',
                                                                           'print',
                                                                           '']},
                                                         'k': 'Optional'}},
                                      'k': 'Object'},
                           'returns': None},
 'Page.setFileInputFiles': {'params': {'campi': {'files': {'di': {'k': 'String'},
                                                           'k': 'Array'},
                                                 'frameId': {'k': 'String'},
                                                 'objectId': {'k': 'String'}},
                                       'k': 'Object'},
                            'returns': None},
 'Page.setInitScripts': {'params': {'campi': {'scripts': {'di': {'campi': {'script': {'k': 'String'},
                                                                           'worldName': {'di': {'k': 'String'},
                                                                                         'k': 'Optional'}},
                                                                 'k': 'Object',
                                                                 'rif': 'pageTypes.InitScript'},
                                                          'k': 'Array'}},
                                    'k': 'Object'},
                         'returns': None},
 'Page.setInterceptFileChooserDialog': {'params': {'campi': {'enabled': {'k': 'Boolean'}},
                                                   'k': 'Object'},
                                        'returns': None},
 'Page.setViewportSize': {'params': {'campi': {'isMobile': {'di': {'k': 'Boolean'},
                                                            'k': 'Optional'},
                                               'screenSize': {'di': {'di': {'campi': {'height': {'k': 'Number'},
                                                                                      'width': {'k': 'Number'}},
                                                                            'k': 'Object',
                                                                            'rif': 'pageTypes.Size'},
                                                                     'k': 'Nullable'},
                                                              'k': 'Optional'},
                                               'viewportSize': {'di': {'campi': {'height': {'k': 'Number'},
                                                                                 'width': {'k': 'Number'}},
                                                                       'k': 'Object',
                                                                       'rif': 'pageTypes.Size'},
                                                                'k': 'Nullable'}},
                                     'k': 'Object'},
                          'returns': None},
 'Runtime.callFunction': {'params': {'campi': {'args': {'di': {'campi': {'objectId': {'di': {'k': 'String'},
                                                                                      'k': 'Optional'},
                                                                         'unserializableValue': {'di': {'k': 'Enum',
                                                                                                        'valori': ['Infinity',
                                                                                                                   '-Infinity',
                                                                                                                   '-0',
                                                                                                                   'NaN']},
                                                                                                 'k': 'Optional'},
                                                                         'value': {'k': 'Any'}},
                                                               'k': 'Object',
                                                               'rif': 'runtimeTypes.CallFunctionArgument'},
                                                        'k': 'Array'},
                                               'executionContextId': {'k': 'String'},
                                               'functionDeclaration': {'k': 'String'},
                                               'returnByValue': {'di': {'k': 'Boolean'},
                                                                 'k': 'Optional'}},
                                     'k': 'Object'},
                          'returns': {'campi': {'exceptionDetails': {'di': {'campi': {'stack': {'di': {'k': 'String'},
                                                                                                'k': 'Optional'},
                                                                                      'text': {'di': {'k': 'String'},
                                                                                               'k': 'Optional'},
                                                                                      'value': {'di': {'k': 'Any'},
                                                                                                'k': 'Optional'}},
                                                                            'k': 'Object',
                                                                            'rif': 'runtimeTypes.ExceptionDetails'},
                                                                     'k': 'Optional'},
                                                'result': {'di': {'campi': {'objectId': {'di': {'k': 'String'},
                                                                                         'k': 'Optional'},
                                                                            'subtype': {'di': {'k': 'Enum',
                                                                                               'valori': ['array',
                                                                                                          'null',
                                                                                                          'node',
                                                                                                          'regexp',
                                                                                                          'date',
                                                                                                          'map',
                                                                                                          'set',
                                                                                                          'weakmap',
                                                                                                          'weakset',
                                                                                                          'error',
                                                                                                          'proxy',
                                                                                                          'promise',
                                                                                                          'typedarray']},
                                                                                        'k': 'Optional'},
                                                                            'type': {'di': {'k': 'Enum',
                                                                                            'valori': ['object',
                                                                                                       'function',
                                                                                                       'undefined',
                                                                                                       'string',
                                                                                                       'number',
                                                                                                       'boolean',
                                                                                                       'symbol',
                                                                                                       'bigint']},
                                                                                     'k': 'Optional'},
                                                                            'unserializableValue': {'di': {'k': 'Enum',
                                                                                                           'valori': ['Infinity',
                                                                                                                      '-Infinity',
                                                                                                                      '-0',
                                                                                                                      'NaN']},
                                                                                                    'k': 'Optional'},
                                                                            'value': {'k': 'Any'}},
                                                                  'k': 'Object',
                                                                  'rif': 'runtimeTypes.RemoteObject'},
                                                           'k': 'Optional'}},
                                      'k': 'Object'}},
 'Runtime.disposeObject': {'params': {'campi': {'executionContextId': {'k': 'String'},
                                                'objectId': {'k': 'String'}},
                                      'k': 'Object'},
                           'returns': None},
 'Runtime.evaluate': {'params': {'campi': {'executionContextId': {'k': 'String'},
                                           'expression': {'k': 'String'},
                                           'returnByValue': {'di': {'k': 'Boolean'},
                                                             'k': 'Optional'}},
                                 'k': 'Object'},
                      'returns': {'campi': {'exceptionDetails': {'di': {'campi': {'stack': {'di': {'k': 'String'},
                                                                                            'k': 'Optional'},
                                                                                  'text': {'di': {'k': 'String'},
                                                                                           'k': 'Optional'},
                                                                                  'value': {'di': {'k': 'Any'},
                                                                                            'k': 'Optional'}},
                                                                        'k': 'Object',
                                                                        'rif': 'runtimeTypes.ExceptionDetails'},
                                                                 'k': 'Optional'},
                                            'result': {'di': {'campi': {'objectId': {'di': {'k': 'String'},
                                                                                     'k': 'Optional'},
                                                                        'subtype': {'di': {'k': 'Enum',
                                                                                           'valori': ['array',
                                                                                                      'null',
                                                                                                      'node',
                                                                                                      'regexp',
                                                                                                      'date',
                                                                                                      'map',
                                                                                                      'set',
                                                                                                      'weakmap',
                                                                                                      'weakset',
                                                                                                      'error',
                                                                                                      'proxy',
                                                                                                      'promise',
                                                                                                      'typedarray']},
                                                                                    'k': 'Optional'},
                                                                        'type': {'di': {'k': 'Enum',
                                                                                        'valori': ['object',
                                                                                                   'function',
                                                                                                   'undefined',
                                                                                                   'string',
                                                                                                   'number',
                                                                                                   'boolean',
                                                                                                   'symbol',
                                                                                                   'bigint']},
                                                                                 'k': 'Optional'},
                                                                        'unserializableValue': {'di': {'k': 'Enum',
                                                                                                       'valori': ['Infinity',
                                                                                                                  '-Infinity',
                                                                                                                  '-0',
                                                                                                                  'NaN']},
                                                                                                'k': 'Optional'},
                                                                        'value': {'k': 'Any'}},
                                                              'k': 'Object',
                                                              'rif': 'runtimeTypes.RemoteObject'},
                                                       'k': 'Optional'}},
                                  'k': 'Object'}},
 'Runtime.getObjectProperties': {'params': {'campi': {'executionContextId': {'k': 'String'},
                                                      'objectId': {'k': 'String'}},
                                            'k': 'Object'},
                                 'returns': {'campi': {'properties': {'di': {'campi': {'name': {'k': 'String'},
                                                                                       'value': {'campi': {'objectId': {'di': {'k': 'String'},
                                                                                                                        'k': 'Optional'},
                                                                                                           'subtype': {'di': {'k': 'Enum',
                                                                                                                              'valori': ['array',
                                                                                                                                         'null',
                                                                                                                                         'node',
                                                                                                                                         'regexp',
                                                                                                                                         'date',
                                                                                                                                         'map',
                                                                                                                                         'set',
                                                                                                                                         'weakmap',
                                                                                                                                         'weakset',
                                                                                                                                         'error',
                                                                                                                                         'proxy',
                                                                                                                                         'promise',
                                                                                                                                         'typedarray']},
                                                                                                                       'k': 'Optional'},
                                                                                                           'type': {'di': {'k': 'Enum',
                                                                                                                           'valori': ['object',
                                                                                                                                      'function',
                                                                                                                                      'undefined',
                                                                                                                                      'string',
                                                                                                                                      'number',
                                                                                                                                      'boolean',
                                                                                                                                      'symbol',
                                                                                                                                      'bigint']},
                                                                                                                    'k': 'Optional'},
                                                                                                           'unserializableValue': {'di': {'k': 'Enum',
                                                                                                                                          'valori': ['Infinity',
                                                                                                                                                     '-Infinity',
                                                                                                                                                     '-0',
                                                                                                                                                     'NaN']},
                                                                                                                                   'k': 'Optional'},
                                                                                                           'value': {'k': 'Any'}},
                                                                                                 'k': 'Object',
                                                                                                 'rif': 'runtimeTypes.RemoteObject'}},
                                                                             'k': 'Object',
                                                                             'rif': 'runtimeTypes.ObjectProperty'},
                                                                      'k': 'Array'}},
                                             'k': 'Object'}}}

EVENTI = {'Browser.attachedToTarget': {'campi': {'sessionId': {'k': 'String'},
                                        'targetInfo': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                                                      'k': 'Optional'},
                                                                 'openerId': {'di': {'k': 'String'},
                                                                              'k': 'Optional'},
                                                                 'targetId': {'k': 'String'},
                                                                 'type': {'k': 'Enum',
                                                                          'valori': ['page']}},
                                                       'k': 'Object',
                                                       'rif': 'browserTypes.TargetInfo'}},
                              'k': 'Object'},
 'Browser.detachedFromTarget': {'campi': {'sessionId': {'k': 'String'},
                                          'targetId': {'k': 'String'}},
                                'k': 'Object'},
 'Browser.downloadCreated': {'campi': {'browserContextId': {'di': {'k': 'String'},
                                                            'k': 'Optional'},
                                       'frameId': {'k': 'String'},
                                       'pageTargetId': {'k': 'String'},
                                       'suggestedFileName': {'k': 'String'},
                                       'url': {'k': 'String'},
                                       'uuid': {'k': 'String'}},
                             'k': 'Object'},
 'Browser.downloadFinished': {'campi': {'canceled': {'di': {'k': 'Boolean'},
                                                     'k': 'Optional'},
                                        'error': {'di': {'k': 'String'},
                                                  'k': 'Optional'},
                                        'uuid': {'k': 'String'}},
                              'k': 'Object'},
 'Network.requestFailed': {'campi': {'errorCode': {'k': 'String'},
                                     'requestId': {'k': 'String'}},
                           'k': 'Object'},
 'Network.requestFinished': {'campi': {'encodedBodySize': {'k': 'Number'},
                                       'protocolVersion': {'di': {'k': 'String'},
                                                           'k': 'Optional'},
                                       'requestId': {'k': 'String'},
                                       'responseEndTime': {'k': 'Number'},
                                       'transferSize': {'k': 'Number'}},
                             'k': 'Object'},
 'Network.requestWillBeSent': {'campi': {'cause': {'k': 'String'},
                                         'frameId': {'di': {'k': 'String'},
                                                     'k': 'Optional'},
                                         'headers': {'di': {'campi': {'name': {'k': 'String'},
                                                                      'value': {'k': 'String'}},
                                                            'k': 'Object',
                                                            'rif': 'networkTypes.HTTPHeader'},
                                                     'k': 'Array'},
                                         'internalCause': {'k': 'String'},
                                         'isIntercepted': {'k': 'Boolean'},
                                         'method': {'k': 'String'},
                                         'navigationId': {'di': {'k': 'String'},
                                                          'k': 'Optional'},
                                         'postData': {'di': {'k': 'String'},
                                                      'k': 'Optional'},
                                         'redirectedFrom': {'di': {'k': 'String'},
                                                            'k': 'Optional'},
                                         'requestId': {'k': 'String'},
                                         'url': {'k': 'String'}},
                               'k': 'Object'},
 'Network.responseReceived': {'campi': {'fromCache': {'k': 'Boolean'},
                                        'fromServiceWorker': {'k': 'Boolean'},
                                        'headers': {'di': {'campi': {'name': {'k': 'String'},
                                                                     'value': {'k': 'String'}},
                                                           'k': 'Object',
                                                           'rif': 'networkTypes.HTTPHeader'},
                                                    'k': 'Array'},
                                        'remoteIPAddress': {'di': {'k': 'String'},
                                                            'k': 'Optional'},
                                        'remotePort': {'di': {'k': 'Number'},
                                                       'k': 'Optional'},
                                        'requestId': {'k': 'String'},
                                        'securityDetails': {'di': {'campi': {'issuer': {'k': 'String'},
                                                                             'protocol': {'k': 'String'},
                                                                             'subjectName': {'k': 'String'},
                                                                             'validFrom': {'k': 'Number'},
                                                                             'validTo': {'k': 'Number'}},
                                                                   'k': 'Object',
                                                                   'rif': 'networkTypes.SecurityDetails'},
                                                            'k': 'Nullable'},
                                        'status': {'k': 'Number'},
                                        'statusText': {'k': 'String'},
                                        'timing': {'campi': {'connectEnd': {'k': 'Number'},
                                                             'connectStart': {'k': 'Number'},
                                                             'domainLookupEnd': {'k': 'Number'},
                                                             'domainLookupStart': {'k': 'Number'},
                                                             'requestStart': {'k': 'Number'},
                                                             'responseStart': {'k': 'Number'},
                                                             'secureConnectionStart': {'k': 'Number'},
                                                             'startTime': {'k': 'Number'}},
                                                   'k': 'Object',
                                                   'rif': 'networkTypes.ResourceTiming'}},
                              'k': 'Object'},
 'Page.bindingCalled': {'campi': {'executionContextId': {'k': 'String'},
                                  'name': {'k': 'String'},
                                  'payload': {'k': 'Any'}},
                        'k': 'Object'},
 'Page.crashed': {'campi': {}, 'k': 'Object'},
 'Page.dialogOpened': {'campi': {'defaultValue': {'di': {'k': 'String'},
                                                  'k': 'Optional'},
                                 'dialogId': {'k': 'String'},
                                 'message': {'k': 'String'},
                                 'type': {'k': 'Enum',
                                          'valori': ['prompt',
                                                     'alert',
                                                     'confirm',
                                                     'beforeunload']}},
                       'k': 'Object'},
 'Page.dispatchMessageFromWorker': {'campi': {'message': {'k': 'String'},
                                              'workerId': {'k': 'String'}},
                                    'k': 'Object'},
 'Page.eventFired': {'campi': {'frameId': {'k': 'String'},
                               'name': {'k': 'Enum',
                                        'valori': ['load', 'DOMContentLoaded']}},
                     'k': 'Object'},
 'Page.fileChooserOpened': {'campi': {'element': {'campi': {'objectId': {'di': {'k': 'String'},
                                                                         'k': 'Optional'},
                                                            'subtype': {'di': {'k': 'Enum',
                                                                               'valori': ['array',
                                                                                          'null',
                                                                                          'node',
                                                                                          'regexp',
                                                                                          'date',
                                                                                          'map',
                                                                                          'set',
                                                                                          'weakmap',
                                                                                          'weakset',
                                                                                          'error',
                                                                                          'proxy',
                                                                                          'promise',
                                                                                          'typedarray']},
                                                                        'k': 'Optional'},
                                                            'type': {'di': {'k': 'Enum',
                                                                            'valori': ['object',
                                                                                       'function',
                                                                                       'undefined',
                                                                                       'string',
                                                                                       'number',
                                                                                       'boolean',
                                                                                       'symbol',
                                                                                       'bigint']},
                                                                     'k': 'Optional'},
                                                            'unserializableValue': {'di': {'k': 'Enum',
                                                                                           'valori': ['Infinity',
                                                                                                      '-Infinity',
                                                                                                      '-0',
                                                                                                      'NaN']},
                                                                                    'k': 'Optional'},
                                                            'value': {'k': 'Any'}},
                                                  'k': 'Object',
                                                  'rif': 'runtimeTypes.RemoteObject'},
                                      'executionContextId': {'k': 'String'}},
                            'k': 'Object'},
 'Page.frameAttached': {'campi': {'frameId': {'k': 'String'},
                                  'parentFrameId': {'di': {'k': 'String'},
                                                    'k': 'Optional'}},
                        'k': 'Object'},
 'Page.frameDetached': {'campi': {'frameId': {'k': 'String'}}, 'k': 'Object'},
 'Page.linkClicked': {'campi': {'phase': {'k': 'Enum', 'valori': ['before', 'after']}},
                      'k': 'Object'},
 'Page.navigationAborted': {'campi': {'errorText': {'k': 'String'},
                                      'frameId': {'k': 'String'},
                                      'navigationId': {'k': 'String'}},
                            'k': 'Object'},
 'Page.navigationCommitted': {'campi': {'frameId': {'k': 'String'},
                                        'name': {'k': 'String'},
                                        'navigationId': {'di': {'k': 'String'},
                                                         'k': 'Optional'},
                                        'url': {'k': 'String'}},
                              'k': 'Object'},
 'Page.navigationStarted': {'campi': {'frameId': {'k': 'String'},
                                      'navigationId': {'k': 'String'}},
                            'k': 'Object'},
 'Page.ready': {'campi': {}, 'k': 'Object'},
 'Page.sameDocumentNavigation': {'campi': {'frameId': {'k': 'String'},
                                           'url': {'k': 'String'}},
                                 'k': 'Object'},
 'Page.uncaughtError': {'campi': {'frameId': {'k': 'String'},
                                  'location': {'campi': {'columnNumber': {'k': 'Number'},
                                                         'lineNumber': {'k': 'Number'},
                                                         'url': {'k': 'String'}},
                                               'k': 'Object',
                                               'rif': 'runtimeTypes.ScriptLocation'},
                                  'message': {'k': 'String'},
                                  'stack': {'k': 'String'}},
                        'k': 'Object'},
 'Page.webSocketClosed': {'campi': {'error': {'k': 'String'},
                                    'frameId': {'k': 'String'},
                                    'wsid': {'k': 'String'}},
                          'k': 'Object'},
 'Page.webSocketCreated': {'campi': {'frameId': {'k': 'String'},
                                     'requestURL': {'k': 'String'},
                                     'wsid': {'k': 'String'}},
                           'k': 'Object'},
 'Page.webSocketFrameReceived': {'campi': {'data': {'k': 'String'},
                                           'frameId': {'k': 'String'},
                                           'opcode': {'k': 'Number'},
                                           'wsid': {'k': 'String'}},
                                 'k': 'Object'},
 'Page.webSocketFrameSent': {'campi': {'data': {'k': 'String'},
                                       'frameId': {'k': 'String'},
                                       'opcode': {'k': 'Number'},
                                       'wsid': {'k': 'String'}},
                             'k': 'Object'},
 'Page.webSocketOpened': {'campi': {'effectiveURL': {'k': 'String'},
                                    'frameId': {'k': 'String'},
                                    'requestId': {'k': 'String'},
                                    'wsid': {'k': 'String'}},
                          'k': 'Object'},
 'Page.workerCreated': {'campi': {'frameId': {'k': 'String'},
                                  'url': {'k': 'String'},
                                  'workerId': {'k': 'String'}},
                        'k': 'Object'},
 'Page.workerDestroyed': {'campi': {'workerId': {'k': 'String'}}, 'k': 'Object'},
 'Runtime.console': {'campi': {'args': {'di': {'campi': {'objectId': {'di': {'k': 'String'},
                                                                      'k': 'Optional'},
                                                         'subtype': {'di': {'k': 'Enum',
                                                                            'valori': ['array',
                                                                                       'null',
                                                                                       'node',
                                                                                       'regexp',
                                                                                       'date',
                                                                                       'map',
                                                                                       'set',
                                                                                       'weakmap',
                                                                                       'weakset',
                                                                                       'error',
                                                                                       'proxy',
                                                                                       'promise',
                                                                                       'typedarray']},
                                                                     'k': 'Optional'},
                                                         'type': {'di': {'k': 'Enum',
                                                                         'valori': ['object',
                                                                                    'function',
                                                                                    'undefined',
                                                                                    'string',
                                                                                    'number',
                                                                                    'boolean',
                                                                                    'symbol',
                                                                                    'bigint']},
                                                                  'k': 'Optional'},
                                                         'unserializableValue': {'di': {'k': 'Enum',
                                                                                        'valori': ['Infinity',
                                                                                                   '-Infinity',
                                                                                                   '-0',
                                                                                                   'NaN']},
                                                                                 'k': 'Optional'},
                                                         'value': {'k': 'Any'}},
                                               'k': 'Object',
                                               'rif': 'runtimeTypes.RemoteObject'},
                                        'k': 'Array'},
                               'executionContextId': {'k': 'String'},
                               'location': {'campi': {'columnNumber': {'k': 'Number'},
                                                      'lineNumber': {'k': 'Number'},
                                                      'url': {'k': 'String'}},
                                            'k': 'Object',
                                            'rif': 'runtimeTypes.ScriptLocation'},
                               'type': {'k': 'String'}},
                     'k': 'Object'},
 'Runtime.executionContextCreated': {'campi': {'auxData': {'campi': {'frameId': {'di': {'k': 'String'},
                                                                                 'k': 'Optional'},
                                                                     'name': {'di': {'k': 'String'},
                                                                              'k': 'Optional'}},
                                                           'k': 'Object',
                                                           'rif': 'runtimeTypes.AuxData'},
                                               'executionContextId': {'k': 'String'}},
                                     'k': 'Object'},
 'Runtime.executionContextDestroyed': {'campi': {'executionContextId': {'k': 'String'}},
                                       'k': 'Object'},
 'Runtime.executionContextsCleared': {'campi': {}, 'k': 'Object'}}
